config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'signup' => 'users#new'
  get 'about' => 'static_pages#about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  root 'static_pages#home'
end

  #   end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50, minimum: 2}
	validates :email, presence: true, length: { minimum: 6, maximum: 200}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

   has_secure_password
   validates :password, length: { minimum: 6 }

   attr_accessor :remember_token

   def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        if remember_digest.nil?
            false
        else
            BCrypt::Password.new(remember_digest).is_password?(remember_token)
        end
    end

    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    @user.level = 0 #all new users start out at level 0
    if @user.save
      log_in @user
      flash[:success] = "You're signed up!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	public def nav_link_to(link:, target_controller:, action: '')
		#<li class="active"><%= link_to 'Home', controller:  'welcome'%></li>
		link = link_to(link, controller: target_controller, action: action)
		if (target_controller == controller.controller_name)
			return content_tag(:li, link, class: "active")
		else
			return content_tag(:li, link)
		end
	end

	def show_messages
		#TODO: Seems rather smelly to simply raw this output, find a better way?
		tags = ""
		flash.each do |message_type, message|
			message_class = "alert alert-" + message_type
			tags+= content_tag(:div, message, class: message_class)
		end
		return tags
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
  	session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
  	user.remember
  	cookies.permanent.signed[:user_id] = user.id
  	cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
  	if (user_id = session[:user_id])
  		@current_user ||= User.find_by(id: user_id)
  	elsif (user_id = cookies.signed[:user_id])
  		user = User.find_by(id: user_id)
  		if user && user.authenticated?(cookies[:remember_token])
  			log_in user
  			@current_user = user
  		end
  	end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
  	!current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
  	session.delete(:user_id)
  	@current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <p>&copy; Paul Colusso, <%= Time.now.year %><br>
   	<small>
   	<% if logged_in? %>
   			<%=link_to "Logout", logout_path, method: :delete%> | 
   			<%=link_to "Profile", user_path(current_user)%>
   		<% else %>
   			<%=link_to "Log In", login_path%>
   		<% end %>
   	 | <%= link_to "Sign Up", signup_path%></small>
    </p>
  </footer> 
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Paul Colusso", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= nav_link_to link: 'Home', target_controller: 'static_pages', action: 'home' %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pol</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container space_vert">
    <%= raw show_messages %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome!</h1>

<p class="lead">The time is <%= Time.now %>, you're in <%= controller.controller_name %></p>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h3>Join</h3>
<p>Join the site. Be aware new users must be approved before becoming active.</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    
      <hr>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>Welcome,  <%= @user.name%></h3>
<%= gravatar_for @user %>

<p>You are currently at clearance level <%= @user.level %>.</p>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<p class="lead">The time is <%= Time.now %>, you're in <%= controller.controller_name %></p>